### PR TITLE
Add token authentication

### PR DESCRIPTION
**Pull request by smathermather**

### CODE REVIEW

**Comment by smathermather** [comment]
Regarding: https://github.com/OpenDroneMap/ClusterODM/issues/53

**Comment by pierotofy** [comment]
Thanks for the PR! It's a good start. :)

image

This won't run as-is; if you need a hand I'll try to find some time in the next few weeks to complete it.

**Comment by smathermather** [comment]
Yes, I tested it and it fails quite quickly. I will need a hand. I am that corgi, I am afraid.

**Comment by pierotofy** [comment]
Merged #54, see if it works for ya.

**Pull request closed without merging**
