### PR TITLE
Update publish-docker.yml

### PR DESCRIPTION
**Pull request by Jeongyong-park**
Add docker tags by dates
#110

### CODE REVIEW

**Comment by pierotofy** [comment]
I don't know if we should keep tags for each push to master (e.g. by date like the proposed changes).

It would be nice to have per-version tags though (can this PR be modified to have that instead?)

**Comment by Jeongyong-park** [comment]
> Thanks for the PR @Jeongyong-park ! I don't know if we should keep tags for each push to master (e.g. by date like the proposed changes).
> 
> It would be nice to have per-version tags though (can this PR be modified to have that instead?)

Thank you for your kindly commented @pierotofy !!

I changed the code with your advice and some github action plugins migrated with latest versions.

However, I don't have Secrets so I haven't tested it properly, but I made it according to the documentation so it should work.

**Comment by Jeongyong-park** [comment]
Tested and fixed.

I made my own public repo and tested with Github Actions.
I will delete the repo in dockerhub after merge.


[https://github.com/Jeongyong-park/ClusterODM/actions/runs/11658165416](https://github.com/Jeongyong-park/ClusterODM/actions/runs/11658165416)

[https://hub.docker.com/repository/docker/kladess/clusterodm/tags](https://hub.docker.com/repository/docker/kladess/clusterodm/tags)

**Comment by pierotofy** [comment]
Thanks @Jeongyong-park ! Looks great. 🙏

**Pull request merged**
